### ISSUE TITLE
Check Mail Now not working

### ISSUE THREAD

**Issue by audio101** [mhogomchungu/qCheckGMail#47] opened 2022-10-27 09:41 UTC
![Screenshot from 2022-10-27 20 40 03](https://user-images.githubusercontent.com/90048453/198250522-0a9836b8-172b-4bcb-9124-e1efceba349e.jpeg)

When account is added, double-clicking tray icon loads above error on browser.

When account is added, clicking/selecting "Check Mail Now" or "Open Mail" from menu, doesn't do anything.

When no account is added, double-clicking tray icon loads GMail inbox (does not auto check/update inbox).

**Comment by mhogomchungu** [comment] 2022-10-27 18:27
What version of qCheckGMail are you using?

**Comment by audio101** [comment] 2022-10-27 20:58
Tested with latest version 2.0.0

**Comment by mhogomchungu** [comment] 2022-10-29 03:23
1. How did you get those error messages?
2. What storage backend are you using? KWallet,gnome secrete or internal storage?
3. I can not reproduce the problem, try to delete your accounts and re-add them.

**Comment by mhogomchungu** [comment] 2022-10-31 05:33
> Loads above error on browser after selecting 'Check Mail Now'.
> 
> No account/double-clicking tray icon loads GMail inbox.

To add accounts, right click the tray icon and then select "Configure Accounts"and then click "Add" in the generated UI.

**Comment by mhogomchungu** [comment] 2022-10-31 13:56
I suspect your problem is because of the below code, the "success" code path is not taken in your case but the application goes on and make network requests without having  "access_token" and gmail complains about this.

The application sets a 30 second timeout for network requests i and suspect you are hitting this timeout.

Go to the app's config file located at ```$HOME/.config/qCheckGMail``` and change
```networkTimeOutInSeconds``` option from 30 to 180 and try again.

https://github.com/mhogomchungu/qCheckGMail/blob/2.0.0/src/qcheckgmail.cpp#L749-L769

**Comment by audio101** [comment] 2022-11-02 03:43
There is no file located at $HOME/.config/qCheckGMail, only a "prefs.xml" located in $HOME./qCheckGMail:

<opt archive_as_read="0"
     atomfeed_address="mail.google.com/mail/feed/atom"
     delay="120000"
     gmail_command="firefox %u"
     language="English"
     nomail_command=""
     notify_command=""
     popup_delay="6000"
     save_passwd="0"
     show_popup_delay="250"
     time_24="0"
     user="">
  <label_delay Inbox="120" />
</opt>

**Comment by audio101** [comment] 2022-11-02 03:49
Did the changes to the config file, same error comes up as before in browser.

**Comment by mhogomchungu** [comment] 2022-11-02 04:43
>When account is added, double-clicking tray icon loads above error on browser.

>When no account is added, double-clicking tray icon loads GMail inbox (does not auto check/update inbox).

Below code explains this behavior. The code is now removed because its no longer possible to open a web browser with a specific account. This is a bug and the git version has a fix for this issue.

https://github.com/mhogomchungu/qCheckGMail/blob/2.0.0/src/qcheckgmail.cpp#L233-L252

> When account is added, clicking/selecting "Check Mail Now" or "Open Mail" from menu, doesn't do anything.

Can you build using git version? It now has a log window and it should be possible to see what data is sent to gmail and what data is received.

When running git version, right click the tray icon and then select "show log window" and then select "check mail now" and then post the contents of the log window

**Comment by audio101** [comment] 2022-11-02 04:51
Can you please provide link to source file/git version?

**Comment by mhogomchungu** [comment] 2022-11-02 05:55
https://github.com/mhogomchungu/qCheckGMail/archive/refs/heads/master.zip

**Comment by audio101** [comment] 2022-11-02 06:00
*************************************************************************
NETWORK REQUEST At Wed Nov 2 16:59:46 2022

GET
https://gmail.googleapis.com/gmail/v1/users/me/labels/INBOX
Authorization:Bearer $ACCESS_TOKEN

*************************************************************************
NETWORK RESPONCE At Wed Nov 2 16:59:46 2022

{
  "id": "INBOX",
  "name": "INBOX",
  "messageListVisibility": "hide",
  "labelListVisibility": "labelShow",
  "type": "system",
  "messagesTotal": 27,
  "messagesUnread": 0,
  "threadsTotal": 22,
  "threadsUnread": 0
}

**Comment by mhogomchungu** [comment] 2022-11-02 06:14
That log say you have no unread emails so the tray icon does not change its color.

Write yourself an email and check again when the tray icon should change its color and the number of unread emails should show on the tray icon.

The tooltip should also change to show new email number if you have any.

**Comment by audio101** [comment] 2022-11-02 06:17
*************************************************************************
NETWORK REQUEST At Wed Nov 2 17:16:51 2022

GET
https://gmail.googleapis.com/gmail/v1/users/me/labels/INBOX
Authorization:Bearer $ACCESS_TOKEN

*************************************************************************
NETWORK RESPONCE At Wed Nov 2 17:16:51 2022

{
  "id": "INBOX",
  "name": "INBOX",
  "messageListVisibility": "hide",
  "labelListVisibility": "labelShow",
  "type": "system",
  "messagesTotal": 28,
  "messagesUnread": 1,
  "threadsTotal": 22,
  "threadsUnread": 1
}

**Comment by audio101** [comment] 2022-11-02 06:19
Still does not show unread emails and tray icon does not change color.

Tool tip does show 1 unread email, however there is still no pop-up notification for unread email(s).

**Comment by mhogomchungu** [comment] 2022-11-02 06:35
This is by design. When unread emails are discovered, three things happen.

1. The tray icon changes color to blue from grey and the number of unread emails should show on in the middle of the blue icon. If the text is too small then you can increase it by changing a config option.
2. The application will also play an audio clip if the option is set in the config option and it is set by default.
3. Tooltip that shows up when mouse cursor is over the tray icon should show what account has how many unread emails.

The app currently does not use a pop up tray notification and that will be a feature request if you want it.

**Comment by audio101** [comment] 2022-11-02 06:38
Yes please, that would be great. What type of popup tray notification could you do?

**Comment by mhogomchungu** [comment] 2022-11-02 08:11
> Still does not show unread emails and tray icon does not change color.
>

Can you post a screenshot of your taskbar that shows a place where the
application tray icon should be.

Pictures explains things much better sometimes.

**Comment by audio101** [comment] 2022-11-02 08:38
![Screenshot from 2022-11-02 19 36 37](https://user-images.githubusercontent.com/90048453/199440259-eef9ee4d-5233-4b69-8128-83db8eb0895e.jpeg)

**Comment by audio101** [comment] 2022-11-02 08:44
![Screenshot from 2022-11-02 19 36 37](https://user-images.githubusercontent.com/90048453/199441549-23d6f3d7-4761-416a-9541-7b1aae537515.jpeg)

qCheckGMail is 2nd from the left, loaded but not visible.

**Comment by guiodic** [comment] 2022-11-02 11:55
I have the same problem, the git version makes possible to open the browser to gmail page but icon is not visible (only blank space)

Operating System: Manjaro Linux
KDE Plasma Version: 5.26.2
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 6.0.6-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: Dell Inc.
Product Name: Inspiron 5502

**Comment by guiodic** [comment] 2022-11-02 12:03
also sound seems not working...

**Comment by mhogomchungu** [comment] 2022-11-02 22:19
The git version now has a working notification sound and a pop up notification and the notification looks like below image in my KDE system.

The notification disappears after 5 seconds and you can change this to make it always visible by setting config option named "NotificationTimeOut" with value "0".

The request to show a notification pop up is sent via DBUS and the notification may look different on your system if your system has implemented the [dbus notification protocol](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#hints).

Try the git version to see if the tray icon is now visible.

![Screenshot_20221103_001324](https://user-images.githubusercontent.com/3496115/199612789-34d2d600-2ba8-4d5c-bef5-49c46dc15f60.png)

**Comment by audio101** [comment] 2022-11-02 22:42
![Screenshot from 2022-11-03 09 40 10](https://user-images.githubusercontent.com/90048453/199616107-060f2a4b-2f15-4fe3-b114-bb09f9e9fc2f.jpeg)

**Comment by audio101** [comment] 2022-11-02 22:43
Tray icon also still not visible even though loaded on system tray.

**Comment by mhogomchungu** [comment] 2022-11-03 05:11
Update again from git and the notification text should no longer show html tags.

About icons not showing, icons are svg icons and the problem you are having could be related to [this](https://askubuntu.com/questions/1433567/xfce-svg-icons-are-not-showing) issue.

Open the app's config file(qCheckGMail.conf) and in it, you will see two entries that look like below
```
newEmailIconColor=qCheckGMail-hasMail
noEmailIconColor=qCheckGMail-hasNoMail
```

Replace "qCheckGMail-hasMail" and "qCheckGMail-hasNoMail" with any icon name from "/usr/share/icons" and then start qCheckGMail and observe your icon shows up.

Will look into changing the icons from svn format to png format.

**Comment by audio101** [comment] 2022-11-03 07:47
html tags issue fixed.

qt5-svg already installed [Manjaro XFCE]

.conf as follows:

[General]
NotificationTimeOut=5000
PortNumber=10000
WindowDimensions_LogWindow=244-262-791-501
alwaysShowTrayIcon=true
audioNotify=true
audioPlayer=mplayer
autostart=true
checkForUpdatesIntervalInMinutes=1
checkingMailIconColor=
clientID=90790670661-5jnrcfsocksfsh2ajnnqihhhk82798aq.apps.googleusercontent.com
clientSecret=LRfPCp9m4PLK-WTo3jHMAQ4i
defaultApplication=browser
displayEmailCount=true
displayEmailCountFontColor=black
displayEmailCountFontFamily=Helvetica
displayEmailCountFontSize=80
errorIconColor=red
interval=30
language=english_US
networkTimeOut=2
networkTimeOutInSeconds=180
newEmailIconColor=blue
noEmailIconColor=grey
pausedEmailIconColor=qCheckGMail-paused
reportOnAllAccounts=true
storageSystem=default kde wallet
visibleIconState=NeedsAttention
visualNotify=true

**Comment by mhogomchungu** [comment] 2022-11-03 13:06
```
errorIconColor=red
newEmailIconColor=blue
noEmailIconColor=grey
```
Above options in your config file are wrong, they should be what is below
```
errorIconColor=qCheckGMail-hasError
newEmailIconColor=qCheckGMail-hasMail
noEmailIconColor=qCheckGMail-hasNoMail
```

Close qCheckGMail and then delete those options and then restart qCheckGMail and report if the icons now show up or not.

**Comment by mhogomchungu** [comment] 2022-11-03 17:28
Update from git and try again, the icon not showing issue should be gone now.

**Comment by audio101** [comment] 2022-11-04 01:29
Icon now visible on system tray & email count :)

Sound working.

**Comment by audio101** [comment] 2022-11-04 02:04
Some future requests to add, if I may:

1. Ability/option to show email title & body text in popup notification box.
2. Ability to click on popup notification box to load inbox.
3. Ability to choose custom tray icons (i.e. for idle, new email, .svg, .png.).

Thanks.

**Comment by mhogomchungu** [comment] 2022-11-04 05:34
1. Answer is [here](https://github.com/mhogomchungu/qCheckGMail/issues/48).

2. API allows it but it will be up to your DE implementation of notification box to show it. Supported parts of the API for xfce are listed [here](https://docs.xfce.org/apps/xfce4-notifyd/spec).
3. It is already possible to change it by modifying the config file. The option to change is ```NotificationTimeOut```. The value is in milliseconds and a value of "0" means "no timeout", A value of "-1" means DE should use its preffered timeout.
4. This is already possible but you have to change them by modifying the config file.

**Comment by mhogomchungu** [comment] 2022-11-04 16:13
Request number two is now in the git version. Closing this issue now as fixed but fill free comment further.


![Screenshot_20221104_190631](https://user-images.githubusercontent.com/3496115/200023835-cd9bfec3-9d94-42eb-850f-dc1b1328d5eb.png)

**Closed by mhogomchungu** 2022-11-04 16:13 UTC

**Comment by mhogomchungu** [comment] 2022-11-05 11:25
New version is out: https://github.com/mhogomchungu/qCheckGMail/releases/tag/2.1.0

**Comment by audio101** [comment] 2022-11-05 11:43
Please also update AUR. Thanks.

**Comment by mhogomchungu** [comment] 2022-11-05 20:57
Updated but i cant test because i dont use arch and will appreciate if you could test and confirm it works and if it doesnt', propose fixes

https://aur.archlinux.org/packages/qcheckgmail

**Comment by audio101** [comment] 2022-11-05 21:41
Manjaro AUR still showing v1.3.0-1, will test after repository is updated.

**Comment by audio101** [comment] 2022-11-06 23:55
qCheckGMail-2.1.0.tar.xz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting qCheckGMail-2.1.0.tar.xz with bsdtar
==> Starting prepare()...
==> Starting build()...
/var/tmp/pamac-build-linux/qcheckgmail/PKGBUILD: line 41: cd: build: No such file or directory
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by mhogomchungu** [comment] 2022-11-07 04:03
Try again, i have updated it

**Comment by audio101** [comment] 2022-11-07 04:10
Working now, finally hehe :)

Good work.

**Comment by audio101** [comment] 2022-11-07 04:18
Just a few issues/comments,

- tray loading browser inbox is single click, when should be double-click instead? (end up always loading 2 inbox tabs).
- instead of having to click on "Open Default Inbox" specific area on popup, can you make it so that clicking on any area of the notification popup box still opens the inbox as well?

**Comment by mhogomchungu** [comment] 2022-11-07 06:21
Clicking on the icon to go to inbox with a web browser appears to work correctly only when you have one account configured and the same account is logged in through the default web browser.

In m case for example, i have two accounts configured and both are logged in through the default web browser and there is currently no way that i know of that will allow me to say from the app which one of the two accounts i want to open a web browser with.

NotificationTimeOut works here as expected, are you restarting qCheckGMail if you are making the change while its running?

**Comment by mhogomchungu** [comment] 2022-11-09 08:01
> tray loading browser inbox is single click, when it should be double-click to open instead? (always end up loading 2 inbox tabs instead of 1).

I have looked and i do not think its possible to tell the difference between a single click and a double click because there is no API for it.

> instead of having to click on "Open Default Inbox" specific area on popup, can you make it so that clicking on any area of the notification popup box still opens the inbox as well?

This is done in the git version. Entries in the notification pop up are now hypelinked if your notification systems supports them and this make it possible to go straight to the inbox that has mail even if its not default account. Clicking the tray icon will continue to open default account.

You said you use xfce, test it but [xfce notification system does not seem to support invoking actions by clicking anywhere on the notifiction widget and a button is required.](https://docs.xfce.org/apps/xfce4-notifyd/spec)
