### ISSUE TITLE
bugs+ feature requests

### ISSUE THREAD

**Issue by audio101** [mhogomchungu/qCheckGMail#45] opened 2021-09-09 11:33 UTC
Bugs:
- loads multiple app instances on tray when app selected again from menu & when there is new or unread mail.
- can only load/edit app menu/options if new mail (app exits from tray if loaded manually when there is no new/read mail).
- if 'Auto Start Application At Log In' is unchecked, app still creates autostart entry.
- autostart 'qCheckGMail -a' causes uncessary loading state of system/mouse pointer on startup.
- new mail preview message & tray icon color change not working.
- 'default kde wallet' & 'qCheckGMail kde wallet' password prompt box not working (N/A to XFCE).

Feature Requests:

- option to be able to view new mail (balloon tray popup or similar adjustable notification), mark as read, &/or delete new mail on server, directly from the app. 
- option to always show on tray (even if no new/unread mail).
- option to change tray icon to user preference (i.e custom icon for new mail, loading, idle, but still show mail count in tray).

tested v1.3.0 (Manjaro XFCE)

**Comment by mhogomchungu** [comment] 2022-08-12 15:53
Starting to work on this one and the git version now forces only one instance to run.

**Comment by mhogomchungu** [comment] 2022-08-15 12:33
It is now possible to change app icons by replacing the ones that are installed or by install custom icons as part of icon theme package(how sure how this works)

Location and names of installed icons when in /usr/ are
```
/usr/share/icons/qCheckGMail-hasNoMail.svg
/usr/share/icons/qCheckGMail-hasError.svg
/usr/share/icons/qCheckGMail-hasMail.svg
```

**Comment by mhogomchungu** [comment] 2022-08-15 12:40
> new mail preview message & tray icon color change not working.

>'default kde wallet' & 'qCheckGMail kde wallet' password prompt box not working (N/A to XFCE).

> option to be able to view new mail (balloon tray popup or similar adjustable notification), mark as read, &/or delete new mail on server, directly from the app.

This is currently not possible, the next version will use google API that allows knowing very little information about a gmail account and the current functionality is the only functionality that is allowed. Any new functionality will cause google to demand to verify the app and they will most likely say no.

I think these are bugs somewhere between KDE and XFCE, its been a while since you reported and try now and see the probem is still there

**Comment by mhogomchungu** [comment] 2022-08-15 13:58
Git version now has a GUI option to always show tray icon

> if 'Auto Start Application At Log In' is unchecked, app still creates autostart entry.
autostart 'qCheckGMail -a' causes uncessary loading state of system/mouse pointer on startup.

The autostart entry always causes the application to auto start at login and when the application is started, it checks its configuration option if it should continue running or not. I did it this way to have a GUI way for a user to configure it to run at start up or now. This is  feature and not a bug and if the initial start is noticeable to you and is trouble some, then the solution is to delete the auto start entry.

I think i have answered all questions and i can close this one.

Feel free to comment if anything comes up

**Closed by mhogomchungu** 2022-08-15 13:58 UTC
