### ISSUE TITLE
Network error after resume from suspend

### ISSUE THREAD

**Issue by vvv-ibm** [mhogomchungu/qCheckGMail#34] opened 2016-06-13 11:10 UTC
It looks like every time I wake my laptop from suspend the status changes to cannot connect to network and it stays there even though I have internet connectivity.
Restarting the app fixes the issue.

Could you try and reproduce on your end? From your code it looks like you detect network connectivity based on empty response from the atom feed? Is it possible that suspending the machine while waiting on a response is causing this?

Thanks!

**Comment by mhogomchungu** [comment] 2016-06-13 11:32
```From your code it looks like you detect network connectivity based on empty response from the atom feed?
```
Yes,I do not know of any other way of checking.

```
Is it possible that suspending the machine while waiting on a response is causing this?
```
I doubt it,suspending while waiting for a response will mean suspending while holding a mutex.Getting a response(even an empty one) means your last network request returned a response. If the last request failed to generate a response,you will get an error that suggests restarting the application because you will then be stuck on a locked muted.

QNetwork has very annoying issues(to me),sometimes,responses are simply not generated when on shaky internet connection resulting in a deadlock i have so far failed to solved and resorted to asking users to restart.

I have a laptop so will check if i can reproduce the error

**Comment by mhogomchungu** [comment] 2016-06-13 12:13
I can not reproduce it here.

Can you update from git and then run the application from the terminal with "-d" option and post the output when you get an empty response.

**Comment by vvv-ibm** [comment] 2016-06-13 12:19
Here you go:

QIODevice::read (QDisabledNetworkReply): device not open
""

"Network access is disabled."

QNetworkReply::NetworkError(UnknownNetworkError)


QIODevice::read (QDisabledNetworkReply): device not open
""

"Network access is disabled."

QNetworkReply::NetworkError(UnknownNetworkError)

**Comment by mhogomchungu** [comment] 2016-06-13 12:24
It looks like QtNetwork is confused somehow. Does the problem remain when you disconnect and reconnect the network?.

What network tool are you using?

**Comment by mhogomchungu** [comment] 2016-06-13 12:50
Can you try again to see if the problem is still there?

I just tried to use what is documented here: http://doc.qt.io/qt-4.8/qnetworkaccessmanager.html#networkAccessible-prop

**Comment by vvv-ibm** [comment] 2016-06-13 15:19
This seems to work, I don't get the network error after resume.
I do see this when I have debug output enabled:

"<?xml version=\"1.0\" encoding=\"UTF-8\"?><feed version=\"0.3\" xmlns=\"
http://purl.org/atom/ns#\"><title>Gmail - Inbox for ibm@varban.net
</title><tagl
ine>New messages in your Gmail Inbox</tagline><fullcount>0</fullcount><link
rel=\"alternate\" href=\"https://mail.google.com/a/varban.net\" type=\"text/
html\" /><modified>2016-06-13T15:11:05Z</modified></feed>"

"Unknown error"

QNetworkReply::NetworkError(NoError)


Not sure if Unknown error is supposed to be there.

I'm running KDE 5 with KF5 plasma and network manager.

Thanks!

**Comment by mhogomchungu** [comment] 2016-06-13 15:24
Yes,its supposed to be there,Those three lines are generated here: https://github.com/mhogomchungu/qCheckGMail/blob/e240dc106704ea0a29a30cbcdb11a6dd47048a05/src/qcheckgmail.cpp#L899

"unknown error" seems to mean "no error".

I am closing this one as "fixed" since recent commit fixed the problem.

**Closed by mhogomchungu** 2016-06-13 15:24 UTC
