### ISSUE TITLE
How to do a KDE5 with QT5 and kwallet support build?

### ISSUE THREAD

**Issue by vvv-ibm** [mhogomchungu/qCheckGMail#28] opened 2015-08-01 16:04 UTC
It looks like QT5 support disables kwallet support in the build?
There is a libkf5wallet-dev package in debian that provides libkwalletbackend5.so which I hope would work out of the box.

Thanks!

**Comment by mhogomchungu** [comment] 2015-08-01 16:31
Yes,i intentionally disabled it because i did the port on a kubuntu image that was meant to show where KDE5 was going and it was a poorly packaged system and i couldnt figure out what package name kwallet was in and what header files i was supposed to include.

I was not impressed with KDE5 and i have not looked at it again. Will revisit the feature again when i try again KDE5 soon.

**Comment by mhogomchungu** [comment] 2015-08-10 14:06
I just made a commit that added support for KWallet in KF5 build.

Can you confirm that it works? The option to enable KF5 is ```-DKF5=true``` so a workable cmake could look like:

```
cmake -DKF5=true  -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr ..
```

I tried it on a kubuntu 14.10 but it should work in debian too.

**Comment by vvv-ibm** [comment] 2015-08-10 21:39
Looks like it's working just fine.
The only thing different seems to be that the ToolTip on the system tray
icon no-longer supports tables so the account email counts are all on a
single line with no new line separators. So I played around a bit and it
seems that it does support <br> tag on top of what's listed here:
http://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/Markup/
but that's about it.

Also, I have not seen a system notification when new emails arrive in a
while, not sure if you're using DBus to send those or even if you're
sending any of those at all.

Thanks for making the changes!

**Comment by mhogomchungu** [comment] 2015-08-11 04:31
This[1] is how i send system notification on new emails.

Do you not get them in the KDE4/Qt4 system or in the KF5/Qt5 system?

[1] https://github.com/mhogomchungu/qCheckGMail/blob/d53b08b0ca206993e81d3b8ecbcb12e4c2413746/src/statusicon.cpp#L158

**Comment by mhogomchungu** [comment] 2015-08-11 04:38
will look into seeing if i can remove the table later on today.

**Comment by mhogomchungu** [comment] 2015-08-11 08:56
I cant seem to be able to get plasma5 desktop on my KDE4 based kubuntu 10.04 so i cant test the tool tip issue.

Are you saying that removing ```<table>``` and ```</table>``` tags makes the tool tip behave the same as in KDE4?

**Comment by vvv-ibm** [comment] 2015-08-11 14:00
No, it doesn't fix it. I added some <br> elements to get it to add new
lines. I didn't remove the table but I don't think it makes any difference
if it's there or not.
So in KDE4 you have each account on new line. In KDE5 it's all accounts on
the same line so adding a <br> at the end of the count string creates new
lines in the tooltip popup. It's not formatted and aligned but it's better.

As for the notifications - I have not received them in KDE4 or 5. I think
the problem might be that the notifyrc file only defines a sound action and
no popup action as mentioned here:
http://api.kde.org/frameworks-api/frameworks5-apidocs/knotifications/html/classKNotification.html

**Comment by mhogomchungu** [comment] 2015-08-11 14:33
Notification works fine here,are you sure you qCheckGMail events enabled in ksystemsettings?

If yes,then the problem could be that the ".notify" file is installed in the wrong place in your system,what does the following command give you?
```
locate .notify
```

What do you think its better?

1. To have the toolkit in KF5 be provided by plasmashell with the <br> tag.
2. To have the toolkit in KF5 be provided by Qt5.This will give a less fancy tooltip but
its entries will be properly aligned.

It should be easy to build with kwallet support without kstatusitemnotifier support.

**Comment by vvv-ibm** [comment] 2015-08-11 15:31
I currently only have the notifyrc in here
/usr/share/qCheckGMail/qCheckGMail.notifyrc and in system settings I can
see qCheckGMail as source but no events listed. When I link the above file
to /usr/share/knotifications5 I can see a second notification source show
up in system settings and that one has the audio event source listed.
None of them produce any notification besides the system tray icon color
changing and adding the unread count.

​I wouldn't worry about that one if it's working on your end.

For the tooltip - I would say whatever method allows you to have a nicely
aligned looking text is what would work the best. ​However, from what I've
read, all distros are slowly moving to the StatusNotifierItem model so it
might be worth using that to ensure future compatibility.

**Comment by mhogomchungu** [comment] 2015-08-11 15:54
The notification worked fine on my KDE4 system.

I have kubuntu 14.10 as one of my test systems and i have so far being unable to completely install KDE5 and plasmashell specifically is missing but i have all the necessary libraries installed and thats why i could port the project to KDE5 and run it but i cant test it because everything shows up through KDE4 panel.

Testing it on a "complete" KF5 system will have to wait a little longer cause i am running low on my data plan for now.

So it looks like the ".notify" file need to be in "/usr/share/knotifications5" in KF5,good to know.

The reason why it played no sound is probably because the audio file named "KDE-Im-New-Mail.ogg" is missing in KDE5.

You can try to replace the sound entry in the .notify file to one of KF5's sound files and see if it will make a difference.

**Comment by vvv-ibm** [comment] 2015-08-11 16:42
No hurry, whenever you get a chance, the app still works fine without
notification popups.
Also it looks like if I edit the notification settings in system settings
it automatically creates a file in ~/.config with following contents:

[Event/qCheckGMail-NewMail]
Action=Sound|Popup
Execute=
Logfile=
Sound=KDE-Im-New-Mail.ogg
TTS=


notice how it has Sound|Popup.

The KDE-Im-New-Mail.ogg file is there, it's part of the kde-runtime-data
package in Debian and I can play it just fine from the Notification system
settings but I don't think the notification event is going out to KDE for
some reason. It might be easier to just send notifications via DBus - this
way you don't need any notifyrc files.

**Comment by mhogomchungu** [comment] 2015-09-01 23:53
I finally managed to install KF5 on an arch install and hence i can now test problems you have identified here.

I just made a commit here[1] that uses the <br> tag to have each email account in its own line.

Will look into the notification problem next.

[1] https://github.com/mhogomchungu/qCheckGMail/commit/8c6a75ad7cd3f00ceedb2354bbcd98a80b79364c

**Comment by mhogomchungu** [comment] 2015-09-16 04:44
I cant seem to be able to reproduce your problem.

I just made a commit that installs "qCheckGMail.notifyrc" to "/usr/share/knotifications5" and qCheckGMail entry shows in in KF5 notification configuration center as expected.

I sent myself an email and an audio file was played when the new email was noticed.I set a pop up to be displayed on new email and a pop up was displayed when another new email was noticed.

I tested this on fedora 22 running KDE Framework 5.13.0.

What version KF5 are you using and you are using it on what distribution.

**Comment by vvv-ibm** [comment] 2015-09-18 02:35
The audio notification actually worked for me but for some reason I thought
that the app also created a customized notification with the unread message
details.
If I change the notification manually in the notification center to include
a popup I do, too, get a popup notification but with no details.

Thanks for looking into this!

**Comment by mhogomchungu** [comment] 2015-09-18 06:26
ok,so things work as expected now since kwallet works in KF5 and KF5's system popups and tray icon pop ups also works.

closing this one as being "fixed" but dont hesitate to respond if anything else comes up.

**Closed by mhogomchungu** 2015-09-18 06:26 UTC

**Comment by mhogomchungu** [comment] 2016-06-06 12:22
Just though i should inform you that its now possible to let qCheckGMail check your email status without giving it your username and password. More info here: https://github.com/mhogomchungu/qCheckGMail/issues/31
